services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - backend:/app
    depends_on:
      - nginx
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - hls:/usr/share/nginx/html/hls
volumes:
  hls:
  backend:
