services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./hls:/app/backend/hls  # Monta el directorio local 'hls'
    depends_on:
      - nginx
    env_file:
      - .env
    restart: unless-stopped  # Añadido para mejor manejo de errores
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:  # Añadido para pasar BASE_IP durante el build
        - BASE_IP=${BASE_IP}
    ports:
      - "80:80"
    volumes:
      - ./hls:/usr/share/nginx/html/hls  # Monta el directorio local 'hls'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${HOSTNAME}
    restart: unless-stopped  # Añadido para mejor manejo de errores
